### ISSUE TITLE
初识服务容器

### ISSUE THREAD

**Issue by KEXUJIAN** [KEXUJIAN/learn_symfony#5]
__部分直接翻译自<a href="http://symfony.com/doc/current/service_container.html" target="_blank"> 官方文档</a>__ 

# 服务
## 剥离可复用代码
在 <a href="https://github.com/KEXUJIAN/learn_symfony/issues/3" target="_blank">*02 控制器*</a> 中曾提到过服务，所谓服务，我理解为封装了一些通用功能代码的，提供调用接口的可复用代码段。正如官方文档举出的提供邮件功能的 *邮件* 类，提供日志记录的 *日志* 类。

如下记录日志场景伪代码
```php
// src/Controller/AController.php
public function foo()
{
    // 1. 获取日志目录路径
    logPath = getLogPath;
    // 2. 检查目录是否存在，不存在创建
    mkdir logPath if logPath is not exists
    // 3. 获取日志文件名，拼接文件路径，检查是否存在
    filePath = logPath + fileName
    mkfile filePath if filePath is not exists
    // 打开日志文件，输入内容
    file = openFile filePath
    appendContent logContent to file
    // 关闭文件
    closeFile file
}
```
如果你只在某一处使用以上代码记录日志（如只在 AController.php 的 foo 方法 中）可能没什么问题，但日志功能是非常常用的，当你写上几十上百遍同样的代码，便自然而然会意识到自己需要将这个功能抽离出来。

写重复代码还只是一个弊端，更惨是当你需要修改写日志的逻辑，真可谓牵一发动全身

```php
// src/Service/Log.php
class Log
{
    public function __construct(string $filePath)
    {
        // 初始化
        // 创建或打开已存在日志文件
    }

    public function write($content)
    {
        // $content 是否为字符串，不是则转为字符串
    }
}
```
然后在这个例子中我们就能愉快地在其他地方调用 `Log` 类，我们要做的只是传入日志文件地址初始化它，然后调用 `write` 方法写日志就好了。

而当写日志的逻辑需要更改时，我们也只需修改 *日志* 类即可
```php
// src/Controller/AController.php
use Service\Log;

public function foo()
{
    $log = new Log($somePath);
    $log->write($content);
}

// src/Controller/BController.php
use Service\Log;

public function foo()
{
    $log = new Log($somePath);
    $log->write($content);
}
```
## 依赖注入
通过抽离出通用功能组成服务对象，我们写出了相比之前更少，也更利于阅读和维护的代码。

但是现在还是存在另一个弊端，那就是所有调用 *Log* 类的地方，都是由我们手动进行服务 (类) 的实例化。

考虑一下，如果我们某些地方的日志需要变更日志地址，或者干脆更换不同的日志服务（比如不写入文件而是写入数据库）呢？我们还是需要笨拙地找到代码中调用服务的地方进行初始化参数的替换，或者更换日志服务类

```php
// 一些冗余代码
public function foo()
{
    // 你可能需要像这样修改几十处的代码
    // 更换地址
    $log = new Log($anotherPath);
    $log->write($content);
    // 更换服务类
    $log = new DataBaseLog();
    $log->write($content);
}
```

而在 `Symfony` 中解决这一问题的方法，就是使用服务容器代替我们管理服务以及依赖，并且通过依赖注入的方式为我们提供服务。

>关于 *依赖注入* 及 *控制反转* 之类的概念这里暂不进行讨论

在我们的项目初始化的时候 (对于 nginx + fpm 的环境来说就是一个请求被 fpm 进程处理的时候) 服务容器会被初始化并读取关于各个服务的配置。

配置文件明确了我们对各个服务的配置，也更有利于服务的依赖的调整

```yaml
# config/services.yaml
services:
    _defaults:
        autowire: true      # 自动注入
        public: false # 不能手动通过 $container->get() 获取服务


    # 所有在 src 目录下的类 (除了定义在 exclude 中的) 会被自动当成服务
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # 显示地配置 Log 服务
    # public = true 可以手动获取
    app.log.default:
        class: App\Log
        public: true
        arguments:
            $filePath: 'some path'

    app.log.another:
        class: App\Log
        public: true
        arguments:
            $filePath: 'another path'
    
    # 当你使用 App\Log $log 这样的类型提示进行注入时
    # 会注入 app.log.default 服务
    App\Log: 'app.log.default'
```

当然此时各服务并不会直接初始化，只有当你第一次调用它的时候，才会被初始化并被注入到你调用的地方。

在学习 `symfony` 的过程中，我主要在类的构造函数和控制器类的 (路由) 方法使用以来注入

```php
// 在 controller 方法中
public function foo(App\Log $logger)
{
    $logger->write($content);
}

// 在构造函数中
class SomeService
{
    private $logger;
    public function __construct(App\Log $logger)
    {
        $this->logger = $logger;
    }
}
```

简单的使用就如同上面这般，是不是很方便，我们省去了自己初始化 `log` 服务的过程，而交由服务容器来帮我们初始化

`symfony` 中可以运行 `php bin/console debug:autowiring` 来了解有哪些支持自动注入的服务。

然后回到之前的两个问题上面来。

通过上面的配置，我们好像解决了同一个 `Log` 服务使用不同的文件写入路径进行初始化的问题。但是我们该如何使用这两个不同的服务呢？

注意到我们的配置中 `public: true` 的配置给了我们手动获取服务的能力，于是，我们可以这样

```php
// 控制器方法中
public function foo()
{
    // 获取 container 实例并获取服务
    $logger = $this->continaer->get('app.log.another');
    // 也可以使用简化的 $this->get($id:String)
}
```

但是这其实并不是最适合的，之后我们会深入探讨 `symfony` 之中是如何 "优雅" 地解决上面的两个问题的。关于服务容器的初体验就先告一段落。
